import 'app/globals.css'
import { Inter } from 'next/font/google'
import Header from 'components/base/Header';
import Footer from 'components/base/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function TestLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <div className='flex min-h-screen flex-col items-center justify-between'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}