'use client';

import { Suspense } from 'react'
import { NavigationEvents } from 'components/ui/navigation-events'
 
import { Inter } from 'next/font/google'
import './globals.css'
import Header from 'components/base/Header'
import Footer from 'components/base/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <div className='flex min-h-screen flex-col items-center justify-between'>
          <Header />
          {children}
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  )
}
